apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: hello-pipeline
description: "Pipeline with staging and prod for Cloud Run"
serialPipeline:
  stages:
  - targetId: staging
  - targetId: prod
